In [2]:
import numpy as np
import pandas as pd

In [3]:
array4d = np.array([[[[1, 2, -3], [4, 5, 600], [7, 8, 9], [10, 11, 12]]]])
maxnum = np.max(array4d)
minnum = np.min(array4d)
#print(array4d.ndim)
print(array4d)
print("The biggest number in this array is... " ,maxnum, '!')
print("The smallest number in this array is... " ,minnum, '!')

[[[[  1   2  -3]
   [  4   5 600]
   [  7   8   9]
   [ 10  11  12]]]]
The biggest number in this array is...  600 !
The smallest number in this array is...  -3 !


In [10]:
# Write a python program to sort words in alphabetical order
#series1 = pd.Series(["John", "Marc", "David", "Bob"])
#series1_re_ordered = series1.sort_values(ascending=True)
#series1_re_ordered

# Modify the above program in order to accept a statement as an input from the user, based on that you sort and display in alphabetical order
user = input("Enter the statement: ")
words = [word.lower() for word in user.split()]
words.sort()

# display the sorted words

print("The sorted words are:")
for word in words:
   print(word)


Enter the statement:  word chheee


The sorted words are:
chheee
word


In [11]:
#opposite direction 
series2_re_ordered = series1.sort_values(ascending=False)
series2_re_ordered

NameError: name 'series1' is not defined

# Write a python program to test if a variable is a list, tuple or a set

In [13]:
thing1 = [1, 2, 3, 4]
thing2 = (1, 2, 3, 4)
thing3 = {1, 2, 3, 4}
def what_is_it(thing):
    thang = type(thing)
    return thang
print(what_is_it(thing1))
print(what_is_it(thing2))
print(what_is_it(thing3))


<class 'list'>
<class 'tuple'>
<class 'set'>


In [3]:
# Write a python program to shuffle cards

deck_of_cards = pd.Series(["Ace of Hearts",
" 2 of Hearts",
" 3 of Hearts",
" 4 of Hearts",
" 5 of Hearts",
" 6 of Hearts",
" 7 of Hearts",
" 8 of Hearts",
" 9 of Hearts",
" 10 of Hearts",
" Jack of Hearts",
" Queen of Hearts",
" King of Hearts",
                             " Ace of Diamonds",
" 2 of Diamonds",
" 3 of Diamonds",
" 4 of Diamonds",
" 5 of Diamonds",
" 6 of Diamonds",
" 7 of Diamonds",
" 8 of Diamonds",
" 9 of Diamonds",
" 10 of Diamonds",
" Jack of Diamonds",
" Queen of Diamonds",
" King of Diamonds",
                             " Ace of Clubs",
" 2 of Clubs",
" 3 of Clubs",
" 4 of Clubs",
" 5 of Clubs",
" 6 of Clubs",
" 7 of Clubs",
" 8 of Clubs",
" 9 of Clubs",
" 10 of Clubs",
" Jack of Clubs",
" Queen of Clubs",
" King of Clubs",
                             " Ace of Spades",
" 2 of Spades",
" 3 of Spades",
" 4 of Spades",
" 5 of Spades",
" 6 of Spades",
" 7 of Spades",
" 8 of Spades",
" 9 of Spades",
" 10 of Spades",
" Jack of Spades",
" Queen of Spades",
" King of Spades"])
#program
shuffled = deck_of_cards.sample(5)
shuffled

17        5 of Diamonds
34           9 of Clubs
5           6 of Hearts
10       Jack of Hearts
25     King of Diamonds
dtype: object

In [7]:
import random, itertools

deck = list(itertools.product(range(1, 14), ["Spades", "Clubs", "Hearts", "Diamonds"]))
random.shuffle(deck)

# draw five cards
print("You got:")
for i in range(5):
   print(deck[i][0], "of", deck[i][1])


You got:
5 of Diamonds
10 of Hearts
1 of Clubs
3 of Diamonds
11 of Hearts


# Square even and odd numbers

In [4]:
import random


In [52]:
evenList = []
oddList = []
list = [0]*10

for i in range(len(list)):
    randNum = random.randint(1, 20)
    list[i] = randNum


for num in range(len(list)):
    if list[num] % 2 == 0:
        evenList.append(list[num])
    else:
        oddList.append(list[num])

for num in range(len(evenList)):
    evNum = evenList[num] * evenList[num] #squares number
    evenList[num] = evNum

for num in range(len(oddList)):
    oddNum = oddList[num] * oddList[num]
    oddList[num] = oddNum
    

print(list)
print("\n")
print(evenList)
print("\n")
print(oddList)        

[4, 1, 3, 10, 18, 2, 4, 16, 2, 1]


[16, 100, 324, 4, 16, 256, 4]


[1, 9, 1]


# Student Marks

In [55]:
studentMarks = [0]*20
Pass = []
reTry = []
fail = []

for i in range(len(studentMarks)):
    randNum = random.randint(0, 100)
    studentMarks[i] = randNum

for grade in range(len(studentMarks)):
    if studentMarks[grade] <= 30:
        fail.append(studentMarks[grade])
    elif studentMarks[grade] >= 31 and studentMarks[grade] <= 69:
        reTry.append(studentMarks[grade])
    else:
        Pass.append(studentMarks[grade])

print(studentMarks)
print("\n")
print(Pass)
print(reTry)
print(fail)
    

[92, 19, 9, 88, 38, 98, 5, 41, 1, 11, 90, 26, 17, 40, 13, 90, 56, 32, 72, 62]


[92, 88, 98, 90, 90, 72]
[38, 41, 40, 56, 32, 62]
[19, 9, 5, 1, 11, 26, 17, 13]
