In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
array1 = np.array(["cheese", "Kai", "Hello"])
print(array1)
print(type(array1))

['cheese' 'Kai' 'Hello']
<class 'numpy.ndarray'>


In [5]:
array2 = np.array((4, 6, 5))
print(array2, type(array2))

[4 6 5] <class 'numpy.ndarray'>


In [6]:
## Arrays can be of different dimensions
# 0D - scalar
# 1D - 
# 2D - 

array0d = np.array(99)
print(array0d, type(array0d), array0d.ndim)
print("\n")

array1d = np.array([2, 3, 6])
print(array1d, type(array1d), array1d.ndim)
print("\n")

array2d = np.array([[2, 3, 6], [3,5,7]])
print(array2d, type(array2d), array2d.ndim)
print("\n")

array3d = np.array([[[1, 2, 3], [10, 20, 30]], [[11, 12, 13], [100, 200, 300]]])
print(array3d, type(array3d), array3d.ndim)

99 <class 'numpy.ndarray'> 0


[2 3 6] <class 'numpy.ndarray'> 1


[[2 3 6]
 [3 5 7]] <class 'numpy.ndarray'> 2


[[[  1   2   3]
  [ 10  20  30]]

 [[ 11  12  13]
  [100 200 300]]] <class 'numpy.ndarray'> 3


In [7]:
array5d = np.array([10, 20, 30, 40], ndmin=5)
print("the dimension of the array is... ", array5d.ndim)
print(array5d)

the dimension of the array is...  5
[[[[[10 20 30 40]]]]]


In [8]:
#shape manipulation - flatten, resize, reshape, stack, split


In [12]:
array3d = np.array([[[1, 2, 3], [10, 20, 30]], [[11, 12, 13], [100, 200, 300]]])
print(array3d.ravel()) ## Flatten concept

[  1   2   3  10  20  30  11  12  13 100 200 300]
(2, 2, 3)


In [14]:
array3d.reshape(6, 2)

array([[  1,   2],
       [  3,  10],
       [ 20,  30],
       [ 11,  12],
       [ 13, 100],
       [200, 300]])

In [19]:
np.hsplit(array3d, 2)

[array([[[ 1,  2,  3]],
 
        [[11, 12, 13]]]),
 array([[[ 10,  20,  30]],
 
        [[100, 200, 300]]])]

In [20]:
array1 = np.array([2, 4, 6, 8, 10, 12])
array2 = np.array([1, 3, 5, 7, 9, 11])


In [23]:
np.hstack((array2, array1))

array([ 1,  3,  5,  7,  9, 11,  2,  4,  6,  8, 10, 12])

In [26]:
array2d = np.array([[2, 3, 6], [3,5,7]])
print(array2d)
print("\n")
print(array2d.transpose())

[[2 3 6]
 [3 5 7]]


[[2 3]
 [3 5]
 [6 7]]


In [27]:
inverse_array = np.array([[4, 3], [1, 6]])
np.linalg.inv(inverse_array)
#Given a square matrix a, return the matrix ainv satisfying dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])

array([[ 0.28571429, -0.14285714],
       [-0.04761905,  0.19047619]])

In [29]:
inverse_array = np.array([[4, 3], [1, 6]])
print(inverse_array)
print(np.trace(inverse_array)) # Trace gives you the sum of diagonal elements

[[4 3]
 [1 6]]
10
